#+TITLE: The wind-forced seasonal cycle of upper-ocean mixing in the Bay of Bengal
#+AUTHOR: D.A. Cherian, E.L. Shroyer, J.N. Moum
#+SETUPFILE: ~/org/notebook.org
#+LATEX_CLASS: dcarticle
#+OPTIONS: toc:nil

#+BEGIN_EXPORT latex
\setcounter{tocdepth}{2}
\renewcommand{\contentsname}{}
\renewcommand{\bibsection}{}
\newcommand{\ML}{_\text{ML}}

% \vspace{-5em}
% \tableofcontents*

\begin{abstract}
We describe the seasonal cycle of turbulent mixing as observed from moored turbulence sensors (χpods) deployed on moorings distributed throughout the Bay of Bengal in the north Indian Ocean during 2014 and 2015.
We find that the seasonal cycle of near-surface turbulent diffusivity (top 45m) in the Bay follows the seasonal cycle in wind forcing.
In the thermocline between \SI{50}{m} and \SI{100}{m}, we repeatedly find that high mixing events coincide with the passage of surface-forced downward propagating near-inertial waves.
The months of March and April, a period of weak wind forcing and low near-inertial shear amplitude, are characterized by near-laminar flow and near-molecular temperature diffusivities for weeks at a time.
Both observations lead us to link the seasonal cycle of thermocline turbulence to the seasonal cycle of near-inertial energy flux in the Bay.
Finally, we combine all χpod observations to form seasonal-mean vertical profiles of diffusivity in the top 100m.
FINAL SENTENCE ABOUT WHY RESULTS MATTER.
\end{abstract}
#+END_EXPORT

* To do list: :noexport:
1. RAMA vs. NRL figure
   - [ ] bootstrap error bars on K_T
2. Need citation for paper with low turbulence measurements in the thermocline.
3. Need citation for Ritabrata's paper
4. Mixing associated with fresh water and salty water?
5. cite:Sardessai2007
6. cite:Vinayachandran2003 say that Ekman pumping pumps up nutrients to force a bloom during the NE monsoon. Maybe I can estimate this flux climatologically?
7. Need to look at climatological Chl-a. Observations are not in the right place for the bloom reported in cite:Vinayachandran2003,Vinayachandran2005

\newpage

* Introduction

The Bay of Bengal is the eastern semi-enclosed basin of the north Indian Ocean.
Large outflows from the Ganga, Brahmaputra, and Irrawady rivers and the mean precipitation maintain strong salinity stratification that is thought to inhibit turbulent mixing and in turn help maintain a relatively shallow oxygen minimum zone citep:Paulmier2009.
Yet mixing /is/ climatologically important.
For one, during the southwest monsoon (May - Sep) the net surface heat flux warms the near-surface ocean on average yet the sea surface temperature (SST) cools citep:Warner2016,Shenoi2002.
Second, the lack of overturning in the Bay implies that its long-time salt balance depends on the Summer Monsoon Current mixing up the relatively saltier Arabian Sea water it brings to the Bay citep:Vinayachandran2013.

The seasonality of wind forcing imprints seasonality on both turbulence (as we will show) and the Bay's circulation (our Figure ref:fig:spatial and citealp:Schott2002).
During the southwest monsoon (May-Sep, SW), precipitation over the Indian subcontinent as well as the Bay peaks and the southwesterly winds are strong.
Episodic strong cyclones that interrupt periods of weak winds characterize the months of October and November (southwest to northeast transition, SWNE).
Between December and February (northeast monsoon, NE), the winds reverse to be northeasterly and strengthen but are weaker than those during the SW monsoon.
The months of March and April are a period of extremely weak winds and weak flows north of 5N (northeast-southwest transition, NESW).
The East Indian Coastal Current spins up at the Bay's western boundary during both monsoons, flowing northward between May and October and then southward between December and April.
In addition, a strong mesoscale cyclone spins up to the east of Sri Lanka during the SW monsoon, termed the Sri Lanka Dome.
In the southwestern Bay, the Summer Monsoon Current threads a pathway between the Sri Lanka Dome to the north and an anticyclone to the south, transporting warm salty Arabian Sea water in to the Bay.
Meanders in the Summer Monsoon Current forced by Rossby waves that trace their origin back to wind fluctuations along the equator make the southwestern Bay a site of strong mesoscale activity during the southwest monsoon (our Figure ref:fig:spatial and citealp:Vinayachandran1998).

- update this paragraph
The seasonal cycle of winds implies a seasonal cycle of near-inertial energy flux $Π$ into the mixed layer.
Figure [[fig:spatial]] shows an estimate of this cycle calculated using a slab ocean mixed layer model with MERRA-2 10-m winds citep:Gelaro2017 and mixed layer depths from the Monthly Isopycnal Upper-Ocean Climatology with Mixed Layers (MIMOC) dataset citep:Schmidtko2013 following cite:Alford2003[fn::Also see Appendix A].
As expected, the SW monsoon sees near-inertial flux nearly throughout the Bay.
Perhaps surprisingly, the largest near-inertial fluxes are confined to latitudes south of 10N until the months of October and November where we see large input along the winter storm track in the Bay.
- These large fluxes are coincident with the region where Arabian Sea water is present in the top 250m...
The most striking aspect of Figure [[fig:spatial]] is the near-complete lack of near-inertial energy flux into the mixed layer during March (northern Bay) and April (northern & southern Bay).
Here we describe year-long observations of turbulence at multiple sites in the Bay (Figure ref:fig:map) and find that the seasonal cycle of winds and near-inertial energy flux described above is imprinted on both near-surface and thermocline turbulence.

#+NAME: fig:spatial
#+CAPTION: (top) Seasonal mean circulation in the Bay of Bengal for the year 2014. Color shows seasonal mean EKE from AVISO; vectors indicate surface currents from seasonally averaged 5-day OSCAR estimate citep:oscar,Bonjean2002. (bottom) Seasonal near-inertial energy input calculated using a slab ocean mixed layer model following cite:Alford2003 as detailed in Appendix A as well as MERRA-2 wind stress vectors.
#+ATTR_LATEX: :width \textwidth
[[file:images/paper1/spatial-maps.pdf]]

#+NAME: fig:map
#+ATTR_LATEX: :width 0.5\textwidth
#+ATTR_HTML: :style width:50%
#+CAPTION: (a) deployment locations of χpods as part of the ASIRI and EBoB programmes. (b, c) χpod deployment depths marked using horizontal lines on climatological T-S profiles from the Argo dataset citep:Roemmich2009 for RAMA and EBoB moorings, respectively.
[[file:images/paper1/map.pdf]]

** outline :noexport:
1. Monsoon seasonal variations blah blah
   1. wind stress + precip + near-surface heating + mention ISOs
   2. SWNE = cyclone season
   3. Use met data in top panel of Figure ref:fig:ramanrl and maps in Figure ref:fig:spatial
   4. Ocean circulation schematic required? Add arrows to Figure ref:fig:map.

2. Importance of mixing (and long-term mixing measurements) in the bay
   1. Something about OMZ
   2. Nutrient fluxes & seasonal cycle of Chl-A
   3. near-surface connections to MISOs
   4. Cyclones and heat-extraction from the Bay.

- cite:Vinayachandran2003: Primary production in the Bay is limited by nutrients, not light. (McGill 1973, Gomes et al 2000). The blooms in this paper are west of the EBoB array. There doesn't seem to be much action by the EBoB array but I need Chl-a data to really know.

* Observations
** χpod

A χpod is a self-contained instrument consisting of two fast-response FP-07 thermistors, a pitot-static tube for high-frequency speed measurements, pressure sensor, compass and accelerometers citep:Moum2009a,Moum2015.
Refinement over the years has resulted in a system that can return records of turbulent temperature fluctuations for up to a year or more.
The two thermistors on the χpod record temperature fluctuations at 100Hz.
Temperature gradient spectra are computed using 1 second intervals of data and are fit to the theoretical spectrum of cite:Kraichnan1968 in the viscous-convective range using an iterative procedure citep:Moum2009a.
This process yields both the turbulent dissipation of kinetic energy $ε$ and the turbulent dissipation of temperature variance $χ$ after using a relationship between $ε$ and $χ$ obtained by assuming $K_T = K_ρ$ i.e. that the turbulent diffusivities of temperature and density are equal, and that mixing efficiency $Γ = 0.2$ for stratified turbulence citep:Moum2009a.
Despite these assumptions, /in-situ/ comparisons between χpod data and ``standard'' vertical microstructure profiles are favorable citep:Perlin2012,Pujiana2018.
Turbulent temperature diffusivity $K_T$, turbulent heat flux $J_q^t$ and turbulent salt flux $J_s^t$ are estimated from a time series of $χ$ using
\begin{equation}
        K_T = \frac{χ/2}{T_z}; \quad J_q^t = - ρ_0\, c_p\, K_T\, T_z; \quad J_s^t = ρ_0 \, K_T \, S_z
\end{equation}
where $T_z, S_z$ are mean background temperature and salinity gradients.
Again, we have assumed that high Reynolds number geophysical turbulence mixes all scalars at the same rate so that $K_T = K_S$.
Inferring $K_T, J_q$ when temperature stratification $T_z$ (subscript $z$ indicates \(z\)-derivative) is sufficiently small can be problematic since these quantities are inversely proportional to $T_z^2$ and $T_z$ respectively.
Our standard procedure is to mask out $χ$ estimates when $T_z < \SI{1e-3}{\celsius\per\metre}$ which can occur frequently with near surface χpods on RAMA moorings that are frequently in the mixed layer.

** The 2014-2015 Bay of Bengal deployment

As part of the U.S. Office of Naval Research's Air Sea Interaction Regional Initiative (ASIRI), Naval Research Laboratory's (NRL) Effects of Bay of Bengal Freshwater Flux on Indian Ocean Monsoon (EBoB) and the Indian government's Ocean Mixing and Monsoons (OMM) projects, a number of χpods were deployed on moorings throughout the Bay (Figure ref:fig:map).
On the Research Moored Array for African-Asian-Australian Monsoon Analysis and Prediction (RAMA) moorings at 12N, 90E (2014, 2015) and 15N, 90 E (2015 only), χpods were deployed at 15m, 30m (2014, 2015) and 45m (2015 only).
These units were usually either in or near the base of the mixed or barrier layers and recorded the wind-forced near-surface cycle of turbulence (Figure [[fig:map]]).

- add proper dates
χpods were also deployed as part of NRL's EBoB array east of Sri Lanka during 2014 and some returned data up to Jan 2015.
The EBoB χpods ended up at a variety of depths but most were in the main thermocline (Figure [[fig:map]]b and citealp:Wijesekera2016a).
These moorings experienced significant blowdown during periods of high currents, up to 50m for a month or two at some moorings, complicating the interpretation of parts of the χpod record.
This region experiences both a significant seasonal cycle in mesoscale EKE associated with the spinup and spindown of the Summer Monsoon Current and a strong seasonal cycle in near-inertial wave input (Figure ref:fig:spatial).
The seasonal cycle of mixing observed here in the southern Bay is quite different relative to that observed by the near-surface χpods on the RAMA moorings in the northern Bay.

In addition, the OMM/WHOI mooring at 18N was heavily instrumented with χpods.
This location is relatively unique because it experiences a lot of freshwater influence from the Ganga-Brahmaputra runoff and the seasonal cycle differs from that at the moorings summarized here.
The seasonal cycle from the OMM/WHOI measurements are presented elsewhere citep:ThakursubmittedGRL.
* Results
** A comparison of near-surface and thermocline mixing
<<sec:ramanrl>>

#+NAME: fig:rama
#+CAPTION: RAMA 12N: Time series of (a) wind stress and local wind-forced near-inertial energy flux; (b) daily averaged $K_T$ and fraction daily coverage; (c) turbulent heat and salt fluxes $J_q^t, J_s^t$. ADD MLD?
[[file:images/paper1/rama12.pdf]]

#+NAME: fig:nrl
#+CAPTION: NRL5: Time series of (a) wind stress and local wind-forced near-inertial energy flux; (b) daily averaged $K_T$ and fraction daily coverage; (c) turbulent heat and salt fluxes $J_q^t, J_s^t$; (d) Near-inertial shear variance and fraction of day where Richardson number Ri < 5.
[[file:images/paper1/nrl5.pdf]]

We begin by contrasting two year-long records, one from the RAMA 12N (12N, 90E) mooring at 15m and the other from the NRL5 mooring (8N, 88.5E) at 104m (Figures ref:fig:rama and ref:fig:nrl).
The two records are at approximately the same longitude.
Figures ref:fig:rama and ref:fig:nrl show daily averaged turbulence quantities as well as daily averaged surface forcing at both moorings.
As mentioned earlier, frequent masking of inferred $K_T, J_q^t, J_s^t$ in mixed layer χpod records means that the term ``daily averages'' is not completely accurate.
Accordingly we show the fraction of the day with valid $K_T$ estimates in gray in Figure [[fig:rama]]b and [[fig:nrl]]b.
Consider the month of February in Figure [[fig:rama]]b.
During weak wind periods the 15m χpod at RAMA 12N (Figure [[fig:rama]]) appears to be within the night-time convective boundary layer whereas during the daytime, solar heating builds up stratification at 15m.
The ``daily average'' is really a ``daytime average'' estimate of $K_T$ and fraction daily coverage is approximately 50%.

The 15m χpod at RAMA 12N recorded a distinct seasonal cycle that mirrors the seasonal cycle in surface wind stress (Figure [[fig:rama]]a).
cite:Warner2016 summarized this record previously and so we limit ourselves to a brief description here.
During the northeast monsoon, wind stress $τ$ of about \SI{0.1}{N/m²} drives turbulence with a daily averaged temperature diffusivity of \SI{1e-4}{m²/s}.
By mid-February the outflow from the Irrawady river arrives at the mooring and the mixed layer shallows to approximately \SI{10}{m}.
The χpod at \SI{15}{m} sees increased turbulent heat flux $J_q^t = ρ c_p K_T T_z$ and turbulent salt flux $J_s^t = ρ K_T S_z$ during this period (Figure [[fig:rama]]c) while the deeper χpod at 30m, in the barrier layer, sees almost no heat and salt flux during this period (not shown).
By March, the weakening wind stress field along with intense surface heating builds up near-surface stratification.
The mixed layer shoals to a depth shallower than 15m and the χpod senses little turbulence.
$K_T$ decreases to \SI{1e-5}{m²/s} associated with near-negligible turbulent heat and salt fluxes.
By May, the strong winds of the southwest monsoon force high mixing, a deeper mixed layer, a hundredfold increase in diffusivity $K_T$ and significant increases in turbulent fluxes of both heat and salt.
Tropical cyclones and storms during the months of October & November drive a 2-3 order of magnitude increase in diffusivity.

The seasonal cycle of thermocline turbulence at 8°N, 88.5°E (NRL5) is significantly different from that of near-surface turbulence at 12N (Figure ref:fig:nrl).
Here sustained high mixing is observed between the months of May and October --- a period of energetic mesoscale activity as well as large near-inertial energy input $Π$ in the southwestern Bay (Figures ref:fig:spatial and [[fig:nrl]]a).
In Figure [[fig:nrl]]a, a local estimate of near-inertial energy flux into the mixed layer $Π$ is computed as $u\ML⋅τ$ using the topmost velocity bin at 8m depth as representative of mixed layer velocity $u\ML$ and daily average $τ$ from Tropflux citep:Kumar2012.
Outside May-October, $K_T$ is consistently below the canonical thermocline value of \SI{1e-5}{m²/s}.
Strikingly, the χpods observe a near-laminar thermocline with near-molecular values of $K_T$ during the month of April.
This observation is consistent with both finestructure- and microstructure-based profiles of turbulence quantities in the Bay.
Finestructure estimates of dissipation estimated using LADCP shear profiles for the I01 section in the Bay of Bengal yield $K_T ≈ \SI{1e-6}{m²/s}$ citep:Kunze2006.
cite:Jinadasa2016 report vertical profiles of $N²$ and turbulent kinetic energy dissipation rate $ε$ from which we infer minimum diffusivity
\begin{equation}
K_T^\text{min} ≈ K_ρ^\text{min} = \frac{Γε^\text{min}}{N²} ≈ \frac{0.2 × \SI{1e-9}{W/kg}}{\SI{1e-3}{s^{-2}}}  ≈\SI{2e-7}{m^2/s},
\end{equation}
assuming again that mixing efficiency $Γ = 0.2$ citep:Gregg2018.

The seasonal cycle in thermocline mixing at 8°N roughly parallels a seasonal cycle in wind stress, near-inertial wind power input and thermocline shear.
Between May and October, SSH anomalies associated with meanders of the Summer Monsoon Current and the wind-forced Sri Lanka Dome propagate through the array and elevate total shear in the water column citep:Wijesekera2016a.
In addition to enhanced shear associated with mesoscale features, there is a clear seasonal cycle in near-inertial shear variance in the thermocline with a seasonal low in April that mirrors the seasonal cycle of near-inertial energy flux at the surface (Figures ref:fig:spatial, [[fig:nrl]]a,d).
This near-inertial variability accounts for roughly 40-60% of total shear variance between \SI{100}{m} and \SI{150}{m} with occasional peaks of 70-80%
The maximum observed diffusivity and maximum observed turbulent fluxes are associated with a particularly strong set of near-inertial wave packets that forced significantly enhanced turbulence at the χpod's depth (July 23 -- August 7, Figure [[fig:nrl]]b,c).
Coarse sampling limits our ability to confidently infer a seasonal cycle in the Richardson number $\Ri$ estimated using 20m-scale shear and $N²$ sampled hourly.
Instead we show a time series of the fraction of day with $\Ri < 5$ expecting that χpods are more likely to observe turbulence when relatively lower values of $\Ri$ occur more frequently (Figure [[fig:nrl]]d).
The arrival of Arabian Sea water in June reduces the stratification and we observe a corresponding increase in occurrences of hours with $\Ri < 5$ up until when stratification rises again in December.
This period of relatively low $\Ri$ coincides with elevated diffusivity $K_T$.
We leave a more detailed examination of the mesoscale, the near-inertial wave field and associated mixing in the Bay's thermocline at 8N to a future paper.

# 1. High NIW shear during NE monsoon but higher stratification presumably suppresses turbulence.
# 2. Are there independent M2 soliton or is the inertial peak losing energy to freely propagating waves.

** An approximate basin-wide vertical profile of diffusivity $K_T$
<<sec:profile>>

There exist nine more approximately year-long records similar to the two described previously and qualitatively much of the seasonal cycle is similar to that represented above.
Rather than discuss them individually, we use all available χpod observations to construct an approximate seasonally averaged vertical profile of hourly averaged temperature diffusivity $K_T$ as follows (Figure ref:fig:vert):

1. We label every averaged $K_T$ measurement with the density value of the parcel observed as well as the depth of measurement. Those measurements made in either the mixed layer or barrier are instead labelled with `ML' and `BL' respectively.
2. We bin these labelled measurements by `ML', `BL' or by density with bin edges [1018, 1021, 1022, 1022.5, 1023, 1023.5, 1024.25, 1029] \SI{}{kg/m^3}.
3. For each season, we construct a probability density function (PDF) of $K_T$ for each bin and calculate the mean and standard deviation of the depths of measurement.
4. The PDFs are now presented at the mean depth of the density bin yielding the vertical profile in Figure ref:fig:vert. Each PDF is also labelled with either `ML', `BL', or the mean density in each bin as appropriate. The vertical bars indicate the standard deviation of depths of observation. Circles and triangles indicate medians and means respectively. The horizontal line at the base of each PDF spans the range between the minimum observed value and the $99^{\text{th}}$ percentile.

Some considerations must be kept in mind while interpreting Figure ref:fig:vert.
First, our definition of seasons need not line up perfectly with periods of relatively high or relatively low winds at every instrument (e.g. Figures ref:fig:rama and ref:fig:nrl).
Second, Figure ref:fig:vert ignores all spatial variability.
The occasional presence of double peaked distributions is the sign of measurements from different regions with differing variability being combined.
Third, our thermocline estimates of mean diffusivity are likely over-estimates of the basin-wide mean between January and April since near-inertial input is significantly larger south of 10N during this period assuming that the slab model prediction in Figure ref:fig:spatial is a good qualitative estimate of seasonal near-inertial flux input.

- Figure references in parenthesis
Despite these caveats, Figure ref:fig:vert presents a useful summary of observed mixing in the Bay and shows that the two records discussed in Section ref:sec:ramanrl are representative.
We see that $K_T$ is always surface intensified and that the northeast and southwest monsoons are periods of relatively high mixing in the top 100m at all observed locations.
Episodically enhanced mixing associated with storms is also observed during October and November.
The transition months of March and April exhibit relatively weaker mixing by an order of magnitude at all observed locations.
During these months, we infer near-molecular values of mixing in multiple χpods deployed in the thermocline as part of the NRL array, just as in Figure [[fig:nrl]]b.
Note that mean values of $K_T$ were $≤ \SI{1e-5}{m²/s}$ for depths deeper than \SI{50}{m} during March and April in Figure ref:fig:vert.
We attribute this to near-complete absence of near-inertial energy input in the southern Bay during April (Figure ref:fig:spatial) and corresponding low levels of near-inertial shear in the southwestern Bay's thermocline (Figure [[fig:nrl]]d).

# Third, given that near-inertial energy input from the wind is significantly larger south of 10N (with the exception of the Oct-Nov storm track, Figure [[fig:spatial]]); and that near-inertial energy propagates equatorward, it is possible that the mixing observed in the thermocline by the EBoB array is larger than what might be representative for the interior Bay north of 10N[fn::should this be moved to the next section?].
# This last point might not be applicable during the months of March and April, which see some along-coast winds in the northern Bay and larger input than the southern Bay (Figure [[fig:spatial]]).
# The mean values below \SI{40}{m} in Figure ref:fig:vert are possibly overestimates of the basin-wide mean.

#+NAME: fig:vert
#+CAPTION: Vertical profile of hourly averaged diffusivity $K_T$ formed by combining all available χpod data in density bins (Section [[sec:profile]]).
file:images/paper1/bay-KT-vert-profile-label.pdf

#+NAME: fig:vert
#+CAPTION: Vertical profile of means of hourly averaged diffusivity $K_T$ along with bootstrap 95% confidence intervals.
file:images/paper1/mean-profile.pdf

* Discussion

Year-long observations of turbulence at multiple sites in the Bay of Bengal (Figure [[fig:map]]) using a moored turbulence platform χpod reveal a seasonal cycle in upper-ocean turbulence.
The seasonal cycle of near-surface turbulence follows from a seasonal cycle in direct wind stress forcing.
The seasonal cycle of thermocline turbulence likely follows from a seasonal cycle of near-inertial energy.
We find that high mixing events in the thermocline coincide with enhanced near-inertial wave shear and the seasonality in near-inertial input as well as near-inertial shear variance is clear (Figures ref:fig:spatial and [[fig:nrl]]a,d).
Our most striking observation is the near-complete lack of mixing in the southwestern Bay's thermocline during the month of April --- a period of low winds, low near-inertial energy flux and low near-inertial shear in the thermocline.

The significance of such low observed mixing is unclear.
Low thermocline diffusivities are predicted by the finestructure internal-wave scaling of cite:Henyey1986 and have been observed previously at low latitudes: $K_ρ ≈ \SIrange[fixed-exponent=-6, scientific-notation=fixed,range-units=brackets]{1e-6}{3e-6}{m^2/s}$ for latitudes south of 10N in cite:Gregg2003.
However, our lowest observed values during March, April at approximately \SIrange{80}{100}{m} depths are lower than those observations.
- I'm currently working on quantifying the seasonal cycle of internal-waveband variance and comparing it to GM.
These observations agree with finestructure shear/strain estimates that use LADCP data citep:Kunze2006

Climate model simulations that account for the latitudinal variation noted in cite:Gregg2003 use a minimum background $K_T ≈ \SI{1e-6}{m^2/s}$ at the equator, an order of magnitude higher than the near-molecular mean $K_T$  we observe between \SIrange{80}{100}{m} at 8°N in the Bay during March and April (for example citealp:Jochum2009,Danabasoglu2012).
Improved upper ocean state representation in the CFSv2 operational forecast model run by the Indian Institute of Tropical Meteorology has been shown to improve rainfall forecasts over central India citep:Koul2018.
cite:Chowdary2016a show this model to be biased cold in the top 80m, biased warm below 100m and have excessive vertical turbulent heat fluxes in the top \SI{200}{m} (/annual mean/).
They link the high mixing bias to excess shear and reduced stratification in the model.
Our observations would suggest that the background mixing in the model might also need to be lowered.
Yet at such low background levels, numerical mixing would dominate.
- I haven't managed to find a paper that relates bias in Jun-Sep predictions to errors in March / April ocean state.
- I don't know whether the IITM model uses the latitudinal variation of background mixing. Frank Bryan at NCAR told me that it's pretty ad-hoc in most climate models.

** Mixing at 8°N along the Summer Monsoon Current (SMC)           :noexport:

#+NAME: fig:smc
#+CAPTION: Vertical profiles binned as in Figure ref:fig:vert and averaged along 8N (NRL3,4,5). Turbulent heat and salt fluxes are important only during May-Nov when high salinity Arabian Sea water is present closer to the surface reflecting the presence of the Summer Monsoon Current / Sri Lanka Dome. High values at 30m are when the χpod is at the base of the mixed layer. MLD is unknown. Axes limits in the last two panels are set so as to focus on the thermocline and avoid the high values near the base of the mixed layer.
[[file:../images/paper1/smc-vertical-flux.pdf]]

The Summer Monsoon Current is the major pipeline for the saline water input necessary to maintain long-term salt balance in the Bay --- see the rise in salinity at around July 1 in Figure [[fig:ramanrl]]g (also citealp:Jain2017,Vinayachandran2013).
Elevated turbulent diffusivity associated with this current is possibly an important contributor to the basin-wide salt budget.
So motivated, we examine the χpods deployed along 8N --- seasonal-mean surface circulation from OSCAR shows this to be the mean latitude of the Summer Monsoon Current (Figure ref:fig:spatial).
Again, we use the methodology of Section [[sec:profile]] to average the turbulent diffusivity and turbulent fluxes in isopycnal bins and construct the seasonal-mean vertical profiles of $K_T, J_q^t$, and $J_s^t$ shown in Figure [[fig:smc]].

As expected, one sees a relative peak in turbulent heat and salt fluxes at depth during the southwest monsoon.
More surprising is the peak salt flux at approximately 60m depth in the density bin (1022.0, 1022.5] \SI{}{kg/m³} that occurs during October and November.
This salt flux coincides with both a set of $M_2$ nonlinear internal tides passing through the NRL3 mooring at 8N, 85.5E, 60m during October and a burst of near-inertial wave energy around Oct-17.
The clockwise shear variance is enhanced at $-f-M_2$.
Again, we see the combination of near-inertial waves and internal nonlinear internal tides modulating turbulence in the Bay's thermocline.
# This particular χpod was in the salinity-stratified isothermal layer and so, the heat fluxes are relatively smaller while the salt flux is relatively larger.

- something about implied flux divergence in Figure [[fig:smc]]. I'm confused. This is an imperfectly sampled profile though.
- Estimate E-P at surface and show that?
- do I need to add a figure showing time series of $J_q^t, J_s^t, |u_z|$ + one panel showing rotary velocity, shear spectrum with shifted peaks?

** Lat/lon variations :noexport:
Some general patterns from Figure ref:fig:spatial.
- RAMA 15N, RAMA 12N are basically consistent modulo freshwater influence from Irrawady.
- NRL stuff is harder to compare because of blowdown. This is motivation for making a vertical profile, binning by isopycnal = next section.
  - Basically, deeper χpods start to see quite low mixing.
  - Higher mixing generally during SW monsoon. Coincides with intense shear associated with SLD followed by an anticyclone citep:Wijesekera2016a. See high EKE in red.
  - Also, strong wind events seem to force NIW packets that propagate downward into thermocline forcing mixing (How many events do I see in all the moorings?)
  - West-East gradients in mesoscale activity, wind forcing
* Conclusions :noexport:
Multiple year-long observations using χpods show that the strong seasonal cycle of wind forcing imprints itself on both near-surface and thermocline turbulence in the Bay of Bengal, influencing the latter through downward propagating near-inertial waves.
- something about really low mixing during NESW

** Next steps = next papers?                                      :noexport:
- Seasonal cycle in internal wave energy?
- Is this recoverable from internal wave - based parameterizations?
  - i.e. does the IW energy level _in the thermocline_ drop during the transition?
  - How do GM + GM-related parameterizations relate to this question? Whalen's dataset?

* Acknowledgments

Funding: ONR YIP, ASIRI

NOAA/PMEL; Sonya Brown

NRL, Hemantha

Johannes Becherer, Sally Warner, Pavan Vutukur, Kerry Latham, Craig van Appledorn.

something about data embargo / availability

* Appendix A: Near-inertial input calculation

Near-inertial energy input $Π$ is calculated following [[cite:Alford2003]]'s spectral solution of the cite:Pollard1970 slab ocean mixed layer using wind speeds from the MERRA-2 reanalysis citep:Gelaro2017 and monthly mean mixed layer depth from the MIMOC climatology citep:Schmidtko2013. There are flaws associated with this calculation citep:Plueddemann2006 but we believe Figure ref:fig:spatial captures the qualitative large-scale spatial variation of $Π$. MERRA-2 does not capture the large wind stresses evident in the TropFlux compilation citep:PraveenKumar2012. However, since TropFlux data is available at daily resolution one cannot calculate the near-inertial input north of approximately 10N, where the inertial period nears 2 days, the Nyquist frequency of the TropFlux winds.

* Appendix B: Treating the χpod as a profiler

* Supplementary Material

1. Table of seasonal means/medians per mooring & also vertical profile.

* References

[[bibliography:bibtexLibrary.bib]]
bibliographystyle:ametsoc2014

\newpage

* old stuff :noexport:
#+NAME: fig:ramanrl
#+ATTR_HTML: :style width:90%
#+CAPTION: (a) Wind stress $τ$ and net surface heat flux $J_q^0$  at RAMA 12N. (b, d) Turbulent heat and salt fluxes $J_q^t, J_s^t$ at RAMA 12N, 15m and NRL5 8N, 105m respectively. (c) Turbulent diffusivity at RAMA 12N, 15m and NRL5 8N, 105m. (e) Wind stress $τ$ and near-inertial energy input $Π$ at NRL5 8N. (f) Fraction of day where we have good turbulence observations. (g, h) Daily average temperature stratification $∂T/∂z$ and salinity $S$ respectively. (i) Shear variance in near-inertial, $M_2$ and $M_4$ frequency bands at NRL5, 8N.
[[file:images/paper1/rama12.pdf]]

* Auto-export :noexport:
# Local variables:
# eval: (add-hook 'after-save-hook 'org-latex-export-to-latex t t)
# end:
